/* kdb_trace.c — gesture (trace) input path.
 *
 * ARCHITECTURE (settled 2026-08-03 by whole-.text scan + stock-blob A/B; supersedes everything
 * this header used to claim).
 *
 * Recognition is a synchronous PUSH, not a poll. The dispatcher at 0x3d9c8 has exactly 15 call
 * sites in the blob and EVERY one is inside ET9KDB_TouchStart/TouchMove/TouchEnd/TouchEndAll/
 * TouchCancel/TouchTimeOut. Nothing scans the result block for finished records. The cutover hands
 * four of those six entry points to us, so once we own them nobody kicks the scorer — and a
 * byte-perfect trace record is inert. That is why successive rounds of record byte-parity work
 * (header fields, session tag, flags, state) changed nothing on device: they were perfecting data
 * that no code reads.
 *
 * So this module no longer writes the result block at all. TouchStart/Move/End accumulate the path,
 * and TouchEnd hands it to ET9KDB_ProcessTrace @0xca4cc — a complete standalone recognizer that
 * builds record[0] itself, arms the dispatch lock, and drives ProcessStoredTouch. It has ZERO
 * callers inside the blob (pure host-facing API), so calling it is safe from reentrancy and, since
 * it is absent from elf_cutover.py's CONTRACT, the blob's definition is the one we reach.
 *
 * TRAP: ProcessTrace bails with 0x66 unless result+0x374 is ZERO (0xca588/0xca58c), and nothing
 * ever decrements that field. The old owned writer set it to 1, permanently disabling the only
 * working entry point. Never write the result block from here again.
 *
 * Corrected facts the old header got wrong:
 *   - record state(+0x44)==2 means "finger down" (TouchStart sets it before the first sample),
 *     NOT "finalized/ready for recognition".
 *   - result+0x374 is an ACTIVE-TOUCH COUNT, not a pending-record count.
 *   - sample[0] is at record+0x50, not +0x5c.
 *   - Touch* take ARRAYS with a count, not scalar x/y/t — see et9kdb.h for the derivation.
 *
 * The live owned decode is owned_pst_v2 (kdb_decode.c segmentation + ambiguous smart-touch sets).
 * The superseded first-cut decoder that used to live here (decode_keyseq + the AW commit hooks,
 * which powered the W3a XT9OWNED scratch comparison) now lives in kdb_decode_legacy.c and is
 * compiled only in the DIFF branch and the host test build -- it is not in the shipped libkb.so.
 */
#include "et9kdb.h"
#include "et9_context.h"
#include "kdb_internal.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include "kdb_freq_en.h"   /* frequency prior: sorted English words + zipf*10, enumerated from the
                            * LDB itself (GENERATED by tools/w5_ldbtable.py) */
/* The owned-recall index stores word indices in ET9U16 and sizes g_rc_list/g_rc_len at 65536;
 * a larger table would silently drop its tail from recall (the 32768->59878 regression). */
_Static_assert(kFreqCountEn <= 65536, "kFreqCountEn exceeds the u16 recall-index cap (65536)");

/* W4: candidate == echo with exactly ONE letter doubled (helo->hello, cofe->coffe)?
 * Dwell EMISSION at decode time lost the natural-mix gate (short-word over-fire,
 * -3.1 net top-1), but the pools already RECALL most double words — the loss was in
 * ranking, where the flat-geometry lookalike (help vs hello) wins on frequency. This
 * targeted bonus fixes doubles where they actually break, with zero decode risk. */
static int is_double_expansion(const char* cand, const char* echo) {
    size_t cl = strlen(cand), el = strlen(echo);
    if (cl != el + 1) return 0;
    for (size_t i = 0; i < el; i++) {
        if (cand[i] != echo[i]) return 0;
        if (cand[i + 1] == cand[i] && !strcmp(cand + i + 2, echo + i + 1)) return 1;
    }
    return 0;
}

/* ---- dwell-evidence double support (VKB doubles workstream, 2026-08-28) --------------------
 * On the VKB corpus the user measurably PAUSES on a doubled letter's key mid-swipe (interior
 * doubles median 567ms vs 233ms plain pass-through; end doubles 589 vs 205), so "time spent
 * within the doubled key's radius" is direct evidence for the double candidate — the signal
 * W4 could not find on the CKB. dwell_at_key sums inter-sample time inside radius r around
 * (kx,ky) over the deposited (authored-space) path; dbl_dwell_support returns 1 iff the
 * candidate has a doubled a-z letter whose key shows >= thr_ms of dwell. */
static float dwell_at_key(const Xt9DecPt* sp, ET9U32 n, float kx, float ky, float r) {
    /* MAX CONTIGUOUS stay, not total: a deliberate double-pause is one continuous visit. A long
     * trace can pass near a key several times and SUM past any threshold (measured: proper's
     * path crediting perrier's rr), but per-visit time stays low — contiguous cuts the corpus
     * false-fire rate 9% -> 1.5% at thr=400 while keeping 88% of true doubles. */
    float best = 0.0f, cur = 0.0f;
    for (ET9U32 i = 1; i < n; i++) {
        float dx = sp[i].x - kx, dy = sp[i].y - ky;
        if (dx * dx + dy * dy <= r * r) {
            cur += (float)(sp[i].t - sp[i - 1].t);
            if (cur > best) best = cur;
        } else cur = 0.0f;
    }
    return best;
}
static int dbl_dwell_support(const ET9KdbLoaded* m, const Xt9DecPt* sp, ET9U32 n,
                             const char* w, int thr_ms) {
    if (!m || !sp || n < 2) return 0;
    for (int i = 1; w[i]; i++) {
        char a = w[i], b = w[i - 1];
        if (a >= 'A' && a <= 'Z') a += 32;
        if (b >= 'A' && b <= 'Z') b += 32;
        if (a != b || a < 'a' || a > 'z') continue;
        for (ET9U16 k = 0; k < m->keyCount; k++) {
            if (m->keys[k].keyCode != (ET9U16)a) continue;
            float r = 0.65f * (float)(m->keys[k].right - m->keys[k].left);
            if (dwell_at_key(sp, n, (float)m->keys[k].cx, (float)m->keys[k].cy, r) >= (float)thr_ms)
                return 1;
            break;
        }
    }
    return 0;
}

/* W6: LIVE LDB frequency of selection-list candidate `gi`, straight from the engine
 * (language-independent, exact vocab-parity, no wordfreq table). Chain recovered by RE
 * (docs/re/): L = *(P)+0x8 (alphaGetSelectionListWord@0x1cf20), the PUBLIC
 * ET9AWSelLstGetWord@0xef7e4(L,&entry,gi) returns a ptr to the internal 616B entry, and
 * the word's frequency is the float32 at entry+0x124 (validated: done 2.4M > some 1.7M >
 * dome 6.9K > helo 1.0). Returns <0 if unavailable (caller falls back to the table). */
/* foff = which frequency field of the 616B entry to use as the prior (W6-C). 0x124 (default)
 * is the LDB+DLM frequency the ranker ships; 0x12c is a larger, related value (~2-3x higher),
 * the candidate CONTEXT-scaled frequency. Selectable (debug.et9.freqoff, read by the caller)
 * so the paragraph-corpus context A/B is a one-prop flip. Context is NOT validatable on
 * isolated-word replays (needs real sentences), so default stays 0x124 until the paragraph
 * gate. */
static float xt9_live_freq(uintptr_t blob_base, void* P, int gi, int foff) {
    if (!P || !blob_base) return -1.0f;
    void* alpha = *(void**)P;
    if (!alpha) return -1.0f;
    typedef int (*fn_slg)(void*, void**, int);
    fn_slg slg = (fn_slg)(blob_base + 0xef7e4u);
    void* ep = 0;
    if (slg((char*)alpha + 0x8, &ep, gi) != 0 || !ep) return -1.0f;
    if (foff != 0x124 && foff != 0x128 && foff != 0x12c) foff = 0x124;
    return *(float*)((char*)ep + foff);
}

/* W6 locale gate: active LDB language via ET9AWLdbGetActiveLanguage@0xd4de0(L, &out),
 * L = *(P)+0x8. Returns the ET9 primary-language id, or -1 if unavailable. English variants
 * enable the English-lexicon pieces (W5 owned recall + the wordfreq-table echo/double
 * heuristics); the LIVE-frequency pool prior is language-independent and always on. */
static int xt9_active_lang(uintptr_t blob_base, void* P) {
    if (!P || !blob_base) return -1;
    void* alpha = *(void**)P;
    if (!alpha) return -1;
    typedef int (*fn_gal)(void*, ET9U32*);
    fn_gal gal = (fn_gal)(blob_base + 0xd4de0u);
    ET9U32 lang = 0;
    if (gal((char*)alpha + 0x8, &lang) != 0) return -1;
    return (int)lang;
}

/* zipf*10 of a lowercase word (0 = unknown => rare/nonword). Binary search over the
 * generated table; NONWORD threshold used by the ranker = 28 (zipf 2.8). */
static int freq_zipf10(const char* w) {
    int lo = 0, hi = kFreqCountEn - 1;
    while (lo <= hi) {
        int mid = (lo + hi) >> 1;
        int c = strcmp(w, kFreqWordsEn[mid]);
        if (c == 0) return (int)kFreqZipfEn[mid];
        if (c < 0) hi = mid - 1; else lo = mid + 1;
    }
    return 0;
}

/* raw LDB rank of a lowercase word (INT_MAX = unknown => treat as rarest). Used ONLY to break an
 * exact score tie toward the more-common (lower-rank) word — pool(1894) over poll(1895), which are
 * geometrically identical as swipes and quantize to the same zipf*10. */
static int freq_rank(const char* w) {
    int lo = 0, hi = kFreqCountEn - 1;
    while (lo <= hi) {
        int mid = (lo + hi) >> 1;
        int c = strcmp(w, kFreqWordsEn[mid]);
        if (c == 0) return (int)kFreqRankEn[mid];
        if (c < 0) hi = mid - 1; else lo = mid + 1;
    }
    return 0x7fffffff;
}

/* ==== W5: trace-native owned recall (plan §3 W5 / §12) =========================================
 * SHARK2-style lexicon recall over the RAW trace: prune the 30k-word table by start/end
 * anchor keys (top-3 nearest each) + ideal-path-vs-arc length ratio, score survivors with
 * xt9kdb_rank_score, and MERGE with the AW tap-corrector pool (union — recall can only rise;
 * the W3/W4 blend arbitrates both pools with identical scoring). Pruning validated offline on
 * the 69 real traces: intended word survives 69/69, median 167 survivors, p90 ~1.2k.
 * This is the piece the discretize->correct pipeline could never provide: pass-through
 * letters (very's r), zigzag drops (question), and corner classes are geometrically invisible
 * in a committed skeleton but alive in the raw trace. */

#define RC_MAX_SCORE 1500      /* survivor cap per gesture (p90 ~1.2k; log when hit) */
#define RC_TOP 8               /* candidates handed to the blend */

static ET9U16 g_rc_list[65536];          /* word indices grouped by (first,last) letter (cap >= table size) */
static ET9U32 g_rc_off[26][27];          /* [f][l] start into g_rc_list; [f][26] = end */
static int    g_rc_built = 0;
static float  g_rc_len[65536];           /* per-word ideal path length (authored space)  */
static const ET9KdbLoaded* g_rc_len_model = 0;
static float  g_rc_kx[26], g_rc_ky[26];  /* letter -> key center, current model */

/* (first,last) bucket of a table word, or 0 if the word does not bucket (shorter than two
 * characters, or an end letter outside a..z). Matches the reference builder's implicit filter:
 * there `a - 'a' != f` never matches for a char outside a..z, so such words were never emitted. */
static int rc_word_bucket(const char* w, int* f, int* l) {
    size_t len = strlen(w);
    if (len < 2) return 0;
    char a = w[0], b = w[len - 1];
    if (a < 'a' || a > 'z' || b < 'a' || b > 'z') return 0;
    *f = a - 'a'; *l = b - 'a';
    return 1;
}

/* REFERENCE builder: the original O(26*26*N) formulation -- one full rescan of the table per
 * letter pair, ~40M strlen calls for the 59,878-word table. Measured 160 ms on the emulator and
 * 1-2 s on the KEY2, paid ON THE MAIN THREAD by the first gesture of the process (touchEnd ->
 * ProcessTrace(OWNED) -> rc_recall). Kept only as the oracle for xt9kdb_recall_index_selfcheck. */
static ET9U32 rc_build_index_reference(ET9U16* list, ET9U32 off[26][27]) {
    ET9U32 n = 0;
    for (int f = 0; f < 26; f++) {
        for (int l = 0; l < 26; l++) {
            off[f][l] = n;
            for (int i = 0; i < kFreqCountEn && n < 65536; i++) {
                const char* w = kFreqWordsEn[i];
                size_t len = strlen(w);
                if (len < 2) continue;
                char a = w[0], b = w[len - 1];
                if (a - 'a' != f || b - 'a' != l) continue;
                list[n++] = (ET9U16)i;
            }
        }
        off[f][26] = n;
    }
    return n;
}

/* LIVE builder: counting sort, O(N). One pass sizes the 676 buckets, prefix sums lay them out
 * contiguously in (first,last) order, one pass places the indices. Within a bucket the words stay
 * in ascending table index -- exactly what the reference emitted -- which the recall loop relies
 * on twice: its RC_MAX_SCORE survivor cap decides WHICH words get scored by bucket order, and its
 * top-RC_TOP insertion keeps the earlier word on an equal geometry score. The selfcheck below
 * asserts the two builders agree byte for byte. */
static ET9U32 rc_build_index_into(ET9U16* list, ET9U32 off[26][27]) {
    ET9U32 cnt[26][26];
    memset(cnt, 0, sizeof cnt);
    for (int i = 0; i < kFreqCountEn && i < 65536; i++) {
        int f, l;
        if (rc_word_bucket(kFreqWordsEn[i], &f, &l)) cnt[f][l]++;
    }
    ET9U32 n = 0;
    ET9U32 cur[26][26];
    for (int f = 0; f < 26; f++) {
        for (int l = 0; l < 26; l++) { off[f][l] = n; cur[f][l] = n; n += cnt[f][l]; }
        off[f][26] = n;
    }
    for (int i = 0; i < kFreqCountEn && i < 65536; i++) {
        int f, l;
        if (rc_word_bucket(kFreqWordsEn[i], &f, &l)) list[cur[f][l]++] = (ET9U16)i;
    }
    return n;
}

static void rc_build_index(void) {
    if (g_rc_built) return;
    ET9U32 n = rc_build_index_into(g_rc_list, g_rc_off);
    g_rc_built = 1;
    XT9KDB_LOGI("ownRecall: index built, %u bucketed words", n);
}

/* Debug/host selfcheck: the live O(N) builder must reproduce the reference builder byte for byte
 * (bucket offsets AND per-bucket order). corrupt != 0 flips one reference entry first, so the
 * negative control proves the comparison can fail. Returns 0 on match; 1 = word-count mismatch,
 * 2 = offset-table mismatch, 3 = list mismatch, -1 = out of memory. Scratch is heap-allocated
 * (2 x 128 KB) and freed; the live index is not touched. */
int xt9kdb_recall_index_selfcheck(int corrupt, unsigned* out_words) {
    ET9U16* refList = (ET9U16*)malloc(65536 * sizeof(ET9U16));
    ET9U16* newList = (ET9U16*)malloc(65536 * sizeof(ET9U16));
    if (!refList || !newList) { free(refList); free(newList); return -1; }
    ET9U32 refOff[26][27], newOff[26][27];
    memset(refList, 0, 65536 * sizeof(ET9U16));
    memset(newList, 0, 65536 * sizeof(ET9U16));
    ET9U32 nr = rc_build_index_reference(refList, refOff);
    ET9U32 nn = rc_build_index_into(newList, newOff);
    if (corrupt && nr > 1) refList[nr / 2] ^= 1;   /* one wrong word index mid-table */
    int rc = 0;
    if (nr != nn) rc = 1;
    else if (memcmp(refOff, newOff, sizeof refOff) != 0) rc = 2;
    else if (memcmp(refList, newList, nr * sizeof(ET9U16)) != 0) rc = 3;
    if (out_words) *out_words = (unsigned)nn;
    free(refList); free(newList);
    return rc;
}

static void rc_refresh_model(const ET9KdbLoaded* m) {
    if (g_rc_len_model == m) return;
    for (int c = 0; c < 26; c++) { g_rc_kx[c] = -1.0f; g_rc_ky[c] = -1.0f; }
    for (ET9U16 i = 0; i < m->keyCount; i++) {
        ET9U16 kc = m->keys[i].keyCode;
        if (kc >= 'a' && kc <= 'z') { g_rc_kx[kc - 'a'] = (float)m->keys[i].cx; g_rc_ky[kc - 'a'] = (float)m->keys[i].cy; }
    }
    for (int i = 0; i < kFreqCountEn && i < 65536; i++) {
        const char* w = kFreqWordsEn[i];
        float L = 0.0f, px = -1.0f, py = -1.0f;
        for (const char* c = w; *c; c++) {
            if (*c < 'a' || *c > 'z') continue;              /* apostrophes ride along */
            float x = g_rc_kx[*c - 'a'], y = g_rc_ky[*c - 'a'];
            if (x < 0.0f) { L = -1.0f; break; }              /* letter not on this KDB */
            if (px >= 0.0f) L += sqrtf((x - px) * (x - px) + (y - py) * (y - py));
            px = x; py = y;
        }
        g_rc_len[i] = L;
    }
    g_rc_len_model = m;
    XT9KDB_LOGI("ownRecall: ideal lengths cached for model %ux%u",
                (unsigned)m->authoredWidth, (unsigned)m->authoredHeight);
}

/* Recall candidates for the CURRENT snapshot. Returns count (<= RC_TOP); fills word indices
 * and geometry scores, best first. */
static int rc_recall(const Xt9DecPt* sp, ET9U32 n, const Xt9DecParams* p,
                     int* outIdx, float* outGeo) {
    if (n < 3) return 0;
    rc_build_index();
    rc_refresh_model(g_kdb_model);
    /* The caller (owned_pst_v2) already mapped the path into AUTHORED space via
     * xt9kdb_sensor_to_authored — do NOT re-apply it here (the SetKeyboardSize stretch is not
     * idempotent; a second application would double-scale VKB paths). */
    float ax0 = sp[0].x, ay0 = sp[0].y;
    float ax1 = sp[n - 1].x, ay1 = sp[n - 1].y;
    ET9SYMB s0[8], s1[8]; ET9U8 fq[8];
    int n0 = xt9kdb_point_to_candidates(g_kdb_model, ax0, ay0, s0, fq, 3);
    int n1 = xt9kdb_point_to_candidates(g_kdb_model, ax1, ay1, s1, fq, 3);
    if (n0 <= 0 || n1 <= 0) return 0;
    float arc = 0.0f, pxx = 0.0f, pyy = 0.0f;
    for (ET9U32 i = 0; i < n; i++) {
        float ax = sp[i].x, ay = sp[i].y;   /* already authored (see above) */
        if (i) arc += sqrtf((ax - pxx) * (ax - pxx) + (ay - pyy) * (ay - pyy));
        pxx = ax; pyy = ay;
    }
    /* score survivors, keep top RC_TOP by geometry */
    float bestGeo[RC_TOP]; int bestIdx[RC_TOP]; int nb = 0;
    int scored = 0, capped = 0;
    for (int a = 0; a < n0 && !capped; a++) {
        if (s0[a] < 'a' || s0[a] > 'z') continue;
        int f = s0[a] - 'a';
        for (int b = 0; b < n1 && !capped; b++) {
            if (s1[b] < 'a' || s1[b] > 'z') continue;
            int l = s1[b] - 'a';
            for (ET9U32 k = g_rc_off[f][l]; k < g_rc_off[f][l + 1]; k++) {
                int wi = g_rc_list[k];
                float L = g_rc_len[wi];
                if (L < 0.0f) continue;
                if (arc >= 40.0f) {
                    if (!(0.45f * arc <= L + 80.0f && L + 80.0f <= 1.9f * arc + 160.0f)) continue;
                } else if (L > 200.0f) continue;
                if (++scored > RC_MAX_SCORE) { capped = 1; break; }
                float g = xt9kdb_rank_score(g_kdb_model, p, sp, n, kFreqWordsEn[wi], 0);
                if (nb < RC_TOP || g < bestGeo[nb - 1]) {
                    int q = (nb < RC_TOP) ? nb++ : (RC_TOP - 1);
                    while (q > 0 && bestGeo[q - 1] > g) {
                        bestGeo[q] = bestGeo[q - 1]; bestIdx[q] = bestIdx[q - 1]; q--;
                    }
                    bestGeo[q] = g; bestIdx[q] = wi;
                }
            }
        }
    }
    if (capped) XT9KDB_LOGF("ownRecall: survivor cap hit (%d scored)", scored);
    for (int i = 0; i < nb; i++) { outIdx[i] = bestIdx[i]; outGeo[i] = bestGeo[i]; }
    return nb;
}

/* Trace-record sessionTag @rec+0x28 = the LOADED KDB's CONTENT CHECKSUM (== NKL header +0x0c), copied
 * per gesture. It is per-KDB, not a constant: uneven-band KDB = 0xBB786DC7, uniform-108 KDB = 0xAF5B3D8D,
 * uniform-150 = 0x27BE5ACF (probe captures 2026-07-05). The 0xBB786DC7 below is the UNEVEN KDB's checksum
 * (our current live layout) and is a FALLBACK only. TODO(cutover): source the tag from the live NKL+0x0c
 * instead of this constant (checksum algorithm still TBD — see docs/2026-07_re-nkl-struct-findings_reference.md). */
#define ET9_SESSION_TAG  0xBB786DC7u
#define MAX_SAMPLES      2560   /* >= the RE-confirmed 2499 blob cap (ET9_TRACE_CAP) */

#if defined(XT9KDB_CUTOVER) && defined(__ANDROID__)
static ET9U32 g_pst_calls;   /* ProcessStoredTouch calls this gesture; see the interpose below */
#endif

/* Per-gesture accumulation buffer. TODO: move into ctx for multi-context/threads. */
static ET9KdbSample g_buf[MAX_SAMPLES];
static ET9U32       g_n;
static ET9U32       g_startT;
static float        g_startX, g_startY;

/* ---- L1: which CONTACT owns the buffer (audit docs/2026-09_kdb-touch-abi_audit.md) -----------
 * There is one path buffer, and the shim hands us a touchId we used to discard entirely. That
 * made two concurrent contacts indistinguishable: a stray finger's TouchMove samples were
 * appended to the real gesture's path, and a stray TouchEnd ran the recognizer over the mix.
 *
 * The chosen semantics is OWNER-FILTERING, not per-pointer sessions. Per-pointer buffers would
 * need a per-pointer recognizer too -- process_trace_impl, the rank snapshot and the deposit
 * sequence are all single-path, and the JNI ranker consumes exactly one capture -- so they would
 * be an ABI change, not a bug fix. Instead:
 *
 *   TouchStart  NEWEST CONTACT WINS -- unchanged from before, deliberately: it is the contract
 *               the CKB gesture arbiter relies on for chained flicks, where a secondary finger
 *               landing starts a fresh trace and the in-flight one is abandoned
 *               (GestureTraceRecorder.kt:62-66). The abandonment is now COUNTED and LOGGED
 *               instead of being silent, and the new contact becomes the owner.
 *   TouchMove   a sample from a contact that is not the owner is DROPPED. This is the actual
 *               corruption the audit found: it used to be appended to someone else's path.
 *   TouchEnd    an end from a non-owner does NOT append its point and does NOT run the
 *               recognizer -- that contact never had a session to finish.
 *   TouchCancel still clears regardless of touchId. That is the pinned contract (the arbiter
 *               cancels a contact it has consumed) and the unstick path, so an owner can never
 *               outlive its gesture: Start / Cancel / Set|ClearTraceInput all release it.
 *
 * Filtering applies ONLY while a session is live. With no owner -- before the first TouchStart,
 * or after an end/cancel -- every entry point behaves exactly as it did, which keeps the
 * out-of-order tolerances pinned by touch_abi_selftest.c section 6, and keeps the VKB tap's
 * cancel-then-end pair (audit L7) as harmless as it was. */
static int    g_session_live;      /* a TouchStart has claimed the buffer */
static ET9U64 g_session_id;        /* the owning touchId; valid while g_session_live */
static ET9U32 g_foreign_drops;     /* contacts rejected/abandoned because they are not the owner */

ET9U32 xt9kdb_foreign_contact_drops(void) { return g_foreign_drops; }

/* ---- L10: the recognizer's failures need an in-band channel ----------------------------------
 * TouchEnd must report ET9STATUS_NONE whatever happened — the JNI shim collapses any non-zero
 * status to `false` in Java and the blob's own dispatcher hardcodes 0 (§1.3). Correct for shim
 * parity, and it means "the recognizer could not run at all" is visible ONLY in logcat. That is
 * exactly how the September 2026 KEY2 regression hid: libkb.so loaded before the blob, the weak
 * ET9KDB_ProcessTrace reference resolved to NULL, and every swipe for the life of that process
 * did nothing while the API kept answering success (see blob_process_trace below).
 *
 * These two counters are that channel. Monotonic for the life of the process, never reset, same
 * shape as xt9kdb_foreign_contact_drops above, and surfaced to Java through
 * Xt9KdbVariant.recognizerUnavailable() / recognizerFailures().
 *
 *   unavailable — process_trace_impl could not reach a recognizer AT ALL (no context, or the
 *                 blob's symbol did not bind). Non-zero means swipe is dead, not merely wrong.
 *   failures    — a recognizer ran and returned a non-NONE status, which TouchEnd then swallowed.
 *
 * A DIFF build never reaches a recognizer by design, so it deliberately counts NEITHER: an
 * unavailability count is only meaningful where a recognizer was supposed to exist. */
static ET9U32 g_rec_unavailable;
static ET9U32 g_rec_failures;
ET9U32 xt9kdb_recognizer_unavailable(void) { return g_rec_unavailable; }
ET9U32 xt9kdb_recognizer_failures(void)    { return g_rec_failures; }

/* 1 when `touchId` may not touch the live session. */
static int foreign_contact(ET9U64 touchId) {
    return g_session_live && touchId != g_session_id;
}

/* Deposit-ranked gesture word (W1): filled in owned_pst_v2, taken once by the bridge per seq.
 * Defined OUTSIDE the CUTOVER guard: xt9kdb_variant_jni.c ships in both modes and calls this, so
 * a CUTOVER-only definition left libxt9kdb.so (the DIFF build) with an undefined symbol. In DIFF
 * nothing ever fills the word, so this correctly reports "no word for this seq". */
static char   g_gesture_word[80];
static ET9U32 g_gesture_word_seq;   /* rank-snapshot seq this word belongs to; 0 = none */

int xt9kdb_take_gesture_word(ET9U32 seq, char* out, int outsz) {
    if (!out || outsz <= 0) return 0;
    if (g_gesture_word_seq == 0 || g_gesture_word_seq != seq || !g_gesture_word[0]) return 0;
    int i = 0; for (; i < outsz - 1 && g_gesture_word[i]; i++) out[i] = g_gesture_word[i];
    out[i] = 0;
    g_gesture_word_seq = 0;            /* consume-once */
    return i;
}

/* Read-only view of the accumulated raw-sensor path. kdb_trace.c owns the buffer; the superseded
 * first-cut decoder (kdb_decode_legacy.c, DIFF/host builds only) reads it through here. */
const ET9KdbSample* xt9kdb_stored_path(ET9U32* count) {
    if (count) *count = g_n;
    return g_buf;
}

ET9STATUS XT9KDB(SetTraceInput)(ET9KDBInfoPtr ctx, ET9BOOL on) { (void)ctx;(void)on; g_n = 0; g_session_live = 0; return ET9STATUS_NONE; }
ET9STATUS XT9KDB(ClearTraceInput)(ET9KDBInfoPtr ctx)          { (void)ctx; g_n = 0; g_session_live = 0; return ET9STATUS_NONE; }

/* RE-confirmed point admission (ET9KDB_TouchMove @0xbc664): a new point within 1.0px of the previous
 * stored sample in BOTH axes is dropped and merged (only its timestamp updates). Hard cap 2499. */
#define ET9_TRACE_CAP 2499
static void push(float x, float y, ET9U32 t) {
    if (g_n) {
        float dx = x - g_buf[g_n-1].x, dy = y - g_buf[g_n-1].y;
        if (dx > -1.0f && dx < 1.0f && dy > -1.0f && dy < 1.0f) {
            g_buf[g_n-1].timestamp = t;   /* near-duplicate: merge (timestamp only) */
            return;
        }
    }
    if (g_n < ET9_TRACE_CAP && g_n < MAX_SAMPLES) {
        g_buf[g_n].x = x; g_buf[g_n].y = y; g_buf[g_n].timestamp = t; g_n++;
    }
}

/* Defined below; must be called instead of the exported ET9KDB_ProcessTrace, which the blob
 * interposes. See the comment on process_trace_impl. */
static ET9STATUS process_trace_impl(ET9KDBInfoPtr ctx);

/* Accumulate one batch. The shim always sends count=1, but the API is an array form and
 * nStart is NOT a start index (the blob zeroes its own index at 0xbbde0 and bounds it by count). */
static void push_batch(const float* xs, const float* ys, const ET9U32* ts, ET9U32 count) {
    for (ET9U32 i = 0; i < count; i++)
        push(xs ? xs[i] : 0.0f, ys ? ys[i] : 0.0f, ts ? ts[i] : 0u);
}

ET9STATUS XT9KDB(TouchStart)(ET9KDBInfoPtr ctx, ET9U64 touchId, const float* xs, const float* ys,
                             const ET9U32* ts, ET9U32 count, ET9U32 nStart) {
    (void)nStart;
    /* Re-publish THIS ctx's model to the legacy global: the spellchecker's secondary engine
     * may have loaded a different KDB since the last gesture (per-context slots,
     * kdb_load_xml.c) and the ctx-less consumers downstream (key_code_at, the JNI ranker
     * over this capture) must see the gesture owner's geometry. */
    { const ET9KdbLoaded* m = xt9kdb_model_for_ctx(ctx); if (m) xt9kdb_set_model(m); }
    /* L2: and this ctx's SCALE, for the same reason — the spellchecker's engine runs its own
     * syncKeyboardLayout -> setKeyboardSize on its own handle, and the ctx-less
     * xt9kdb_sensor_to_authored must map this gesture with the gesturing keyboard's stretch. */
    xt9kdb_publish_ctx_scale(ctx);
    /* L1: a second contact landing mid-gesture still takes the buffer (newest wins — the gesture
     * arbiter's chained-flick contract), but the abandonment is no longer silent. Edge brushes at
     * the sensor's right margin have been observed landing at x=1080; this counter plus the log
     * line are how one tells such a brush apart from a real chained flick in a TRACEPT dump. The
     * abandoned contact's later moves and lift can no longer reach this path — see foreign_contact. */
    if (foreign_contact(touchId)) {
        g_foreign_drops++;
        XT9KDB_LOGI("TouchStart: contact %llu abandons in-flight contact %llu (n=%u)",
                    (unsigned long long)touchId, (unsigned long long)g_session_id, g_n);
    }
    g_session_live = 1;
    g_session_id   = touchId;
    g_n = 0;
#if defined(XT9KDB_CUTOVER) && defined(__ANDROID__)
    g_pst_calls = 0;              /* per-gesture, so the PSt log stays readable */
#endif
    if (count && xs && ys) { g_startX = xs[0]; g_startY = ys[0]; g_startT = ts ? ts[0] : 0u; }
    push_batch(xs, ys, ts, count);
    XT9KDB_LOGI("TouchStart n=%u x=%.1f y=%.1f t=%u", g_n, (double)g_startX, (double)g_startY, g_startT);
    return ET9STATUS_NONE;
}

ET9STATUS XT9KDB(TouchMove)(ET9KDBInfoPtr ctx, ET9U64 touchId, const float* xs, const float* ys,
                            const ET9U32* ts, ET9U32 count, ET9U32 nStart) {
    (void)ctx; (void)nStart;
    /* L1: samples from a contact that does not own the live session never reach the path. */
    if (foreign_contact(touchId)) { g_foreign_drops++; return ET9STATUS_NONE; }
    push_batch(xs, ys, ts, count);
    return ET9STATUS_NONE;
}

/* Trail-point dump gate. Its OWN sysprop (log.tag.XT9Trace), deliberately not the Java-side
 * log.tag.XT9Input: those Java logs fire per touch SAMPLE and their overhead can drop samples,
 * changing the recognition being measured. This dump runs inside TouchEnd AFTER the recognizer
 * has already run, so it observes without perturbing. Checked once per process. */
/* Sysprops are Android-only; the offline suite builds this file on the host, where the header does
 * not exist. Guarding here (rather than omitting the tests) keeps run_tests.sh building. */
/* off_char is the OFF MARKER, not the ON marker: the prop reads as 1 for ANY first byte other
 * than off_char. Every caller here must therefore pass '0'. A flag that shipped with '1' here had
 * its sense inverted -- `setprop <flag> 1` read as OFF and `setprop <flag> 0` read as ON (that was
 * the shipped state of debug.et9.ownpst before its first-cut decoder was retired). */
/* The sense, as one pure function so the host suite can pin it: a SET value is ON unless its
 * first byte is the OFF marker. (L11: log.tag.XT9Trace was passing '\0' here, so `setprop
 * log.tag.XT9Trace 0` turned the dump ON. Every caller now uses XT9_PROP_OFF_CHAR.) */
int xt9kdb_prop_flag_parse(const char* value, char off_char) {
    if (!value || !value[0]) return 1;   /* set to the empty string: still "set" */
    return value[0] == off_char ? 0 : 1;
}
#ifdef __ANDROID__
#include <sys/system_properties.h>
static int read_prop_flag(const char* name, int dflt, char off_char) {
    char v[PROP_VALUE_MAX];
    if (__system_property_get(name, v) <= 0) return dflt;
    return xt9kdb_prop_flag_parse(v, off_char);
}
#else
static int read_prop_flag(const char* name, int dflt, char off_char) {
    (void)name; (void)off_char; return dflt;
}
#endif

int xt9kdb_trace_dump_enabled(void) {
    static int cached = -1;
    if (cached < 0) cached = read_prop_flag("log.tag.XT9Trace", 0, XT9_PROP_OFF_CHAR);
    return cached;
}

ET9STATUS XT9KDB(TouchEnd)(ET9KDBInfoPtr ctx, ET9U64 touchId, const float* xs, const float* ys,
                           const ET9U32* ts, ET9U32 count) {
    /* L1: a non-owner's lift neither extends nor recognizes someone else's path. Reported as
     * success like every other TouchEnd — the shim collapses a non-zero status to `false` in
     * Java and the baseline never does that. */
    if (foreign_contact(touchId)) {
        g_foreign_drops++;
        XT9KDB_LOGI("TouchEnd: contact %llu is not the session owner %llu — ignored (n=%u)",
                    (unsigned long long)touchId, (unsigned long long)g_session_id, g_n);
        return ET9STATUS_NONE;
    }
    g_session_live = 0;                 /* this contact's session is over */
    push_batch(xs, ys, ts, count);
    ET9STATUS st = process_trace_impl(ctx);
    /* Deliberately NOT propagated. The JNI shim does `cmp w0,#0; cset w0,eq` (0x22a58), so a
     * non-zero status flips NuanceSDK.touchEnd() to false in Java. The baseline never does that:
     * the blob's dispatcher returns 0 hardcoded. Log the status, report success. */
    XT9KDB_LOGI("TouchEnd n=%u -> recognizer status=%d", g_n, (int)st);
    /* Diagnostic trail dump: raw sensor point, authored-space mapping, and per-point
     * key resolution. Consumed by tools/trail_grid_analysis.py for swipe calibration. */
    if (xt9kdb_trace_dump_enabled()) {
        for (ET9U32 i = 0; i < g_n; i++) {
            float ax, ay;
            int kc = xt9kdb_key_code_at(g_buf[i].x, g_buf[i].y, &ax, &ay);
            XT9KDB_LOGI("TRACEPT %u/%u raw=%.1f,%.1f auth=%.1f,%.1f key=%d t=%u",
                        (unsigned)i, (unsigned)g_n,
                        (double)g_buf[i].x, (double)g_buf[i].y,
                        (double)ax, (double)ay, kc, g_buf[i].timestamp);
        }
    }
    return ET9STATUS_NONE;
}

/* ---- L9: the two session TERMINATORS must release the session --------------------------------
 * Both used to be pure `return NONE` stubs. Once L1 gave the buffer an OWNER that was no longer
 * merely untidy: a terminator that leaves g_session_live set leaves the foreign-contact filter
 * ARMED, so after the engine core abandons a trace every other contact's moves are dropped as
 * intruders until a TouchStart or TouchCancel happens to clear it. Releasing the owner is the
 * whole fix; the PATH is deliberately kept, exactly as TouchEnd keeps it, because the deposited
 * points must stay readable (GetKeyPositionByStoredTouch, the TRACEPT dump, the ranker snapshot).
 * Only TouchStart / TouchCancel / Set|ClearTraceInput clear the path — §3.1 of the audit.
 *
 * REACHABILITY: on the shipped blob neither symbol is ever called — they are not in CONTRACT and
 * the blob has no reference to them of any kind (elf_cutover.py INERT_NO_CALLERS, measured
 * 2026-09-20), so L9's "the engine core abandons a session behind our back" cannot happen there.
 * This is for the DIFF mirror and the offline suite, which do call them, and so that the owned
 * module's own lifecycle is coherent if the ABI ever reaches us. */
ET9STATUS XT9KDB(TouchEndAll)(ET9KDBInfoPtr ctx)  { (void)ctx; g_session_live = 0; return ET9STATUS_NONE; }
/* Clears regardless of touchId — the pinned contract (the gesture arbiter cancels a contact it has
 * consumed) and the path that always releases a session. A cancel arriving from a contact that is
 * not the owner is counted, so the mismatch is visible rather than silent. */
ET9STATUS XT9KDB(TouchCancel)(ET9KDBInfoPtr ctx, ET9U64 touchId) {
    (void)ctx;
    if (foreign_contact(touchId)) g_foreign_drops++;
    g_session_live = 0;
    g_n = 0;
    return ET9STATUS_NONE;
}
ET9STATUS XT9KDB(TouchTimeOut)(ET9KDBInfoPtr ctx) { (void)ctx; g_session_live = 0; return ET9STATUS_NONE; }

/* ---- ProcessStoredTouch interpose (INVESTIGATION, 2026-08-12) ----------------------------------
 * ProcessTrace drives the real decoder through this symbol, in a loop, setting fields at
 * result+0x360/+0x364 before each call. Two contracts are unknown and neither is decidable from the
 * disassembly, because the addressing is identical either way:
 *
 *   1. Whether +0x360/+0x364 are a control prefix or the first fields of record[0]. The record
 *      array base is ALSO +0x360 (stride 0x7568), so `base + 0x360 + idx*0x7568` reads the same
 *      for both. TRACE_RESULT_REGION.md flags this as open and notes one dump settles it.
 *   2. ProcessStoredTouch's arity/semantics, and what ProcessTrace varies per iteration.
 *
 * This pass-through answers both by observation: log the arguments and the record window on every
 * call, then correlate record +0x50/+0x54 against the touchdown we already log. If they hold the
 * gesture's start point, +0x360 IS record[0].
 *
 * The blob keeps doing the decoding — we call its orphaned original by ADDRESS. Calling it by
 * symbol would be the interposition trap check_interposition.sh exists for: we define this symbol
 * ourselves, so the name would resolve back into our own code. */
#if defined(XT9KDB_CUTOVER) && defined(__ANDROID__)
#include <link.h>
#include <stdint.h>

#define BLOB_PST_VADDR 0xc65b0u

typedef ET9STATUS (*xt9_blob_pst_fn)(void*, ET9U64, void*, ET9U64, ET9U64, ET9U64, ET9U64, ET9U64);
static xt9_blob_pst_fn g_blob_pst;
static int             g_blob_pst_done;

static int xt9_find_blob_pst_cb(struct dl_phdr_info* info, size_t size, void* out) {
    (void)size;
    if (info->dlpi_name && strstr(info->dlpi_name, "libnative-lib.so")) {
        *(uintptr_t*)out = (uintptr_t)info->dlpi_addr;
        return 1;
    }
    return 0;
}

/* debug.et9.owndecode: 0/unset = blob decodes (default); 2 = SHADOW (owned decoder runs in both
 * parity and per-row modes and LOGS next to the blob's result — compute only, the blob's WSI
 * stands); 1 = owned decode live (NOT yet wired — falls back to shadow with a warning).
 * Cached at first use: set the prop, then force-stop. */
/* Default decode path when no prop is set. DEBUG builds (the owner's daily driver) default to the
 * OWNED decoder+ranker so it survives reboots (setprops don't persist); RELEASE stays on the blob
 * until the §1 promotion bar is met (sitting-2 hold-out still pending as of 2026-08-19). A prop
 * (debug.et9.owndecode / .ownrankc) still overrides either way. */
#ifdef NDEBUG
#define OWNED_DEFAULT 0
#else
#define OWNED_DEFAULT 1
#endif

static int owndecode_mode(void) {
    static int cached = -1;
    if (cached < 0) {
#ifdef __ANDROID__
        char v[PROP_VALUE_MAX];
        cached = (__system_property_get("debug.et9.owndecode", v) > 0 && v[0] >= '0' && v[0] <= '9')
                     ? (v[0] - '0') : OWNED_DEFAULT;
#else
        cached = 0;
#endif
    }
    return cached;
}

ET9STATUS XT9KDB(ProcessStoredTouch)(void* a0, ET9U64 a1, void* a2, ET9U64 a3,
                                     ET9U64 a4, ET9U64 a5, ET9U64 a6, ET9U64 a7) {
    if (!g_blob_pst_done) {
        uintptr_t bias = 0;
        g_blob_pst_done = 1;
        dl_iterate_phdr(xt9_find_blob_pst_cb, &bias);
        if (bias) g_blob_pst = (xt9_blob_pst_fn)(bias + BLOB_PST_VADDR);
        XT9KDB_LOGI("PSt trampoline: bias=0x%lx -> %p", (unsigned long)bias, (void*)g_blob_pst);
    }

    /* Self-validating: only walk to the trace object if a0 really is the ctx (its magic sits at
     * +0x58), so a wrong guess about the argument order degrades to a log line, not a crash. */
    if (xt9kdb_trace_dump_enabled() && g_pst_calls < 16u) {
        XT9KDB_LOGI("PSt#%u args a0=%p a1=%llu a2=%p a3=%llu a4=%llu",
                    g_pst_calls, a0, (unsigned long long)a1, a2,
                    (unsigned long long)a3, (unsigned long long)a4);
        if (a0 && *(ET9U16*)((char*)a0 + 0x58) == 0x1428u) {
            char* trace = *(char**)((char*)a0 + 0x30);
            if (trace) {
                char* res = trace + 0x49000;
                XT9KDB_LOGI("  hdr +360=%08x +364=%08x +368=%08x +36c=%08x +370=%08x +374=%08x",
                            *(ET9U32*)(res+0x360), *(ET9U32*)(res+0x364), *(ET9U32*)(res+0x368),
                            *(ET9U32*)(res+0x36c), *(ET9U32*)(res+0x370), *(ET9U32*)(res+0x374));
                /* record[0] under the "array starts at +0x360" reading: tag/seq/count/startXY. */
                /* Sample-array offset: the notes say +0x5c, the code header says +0x50, and both
                 * fit a dump of +0x50/+0x54 because those equal the touchdown either way. This
                 * separates them: if the array starts at +0x5c then +0x5c REPEATS +0x50; if it
                 * starts at +0x50 then +0x5c is sample[1].x and must differ. */
                XT9KDB_LOGI("  samp +50=(%.1f,%.1f) t=%u | +5c=(%.1f,%.1f) t=%u | +68=(%.1f,%.1f)",
                            (double)*(float*)(res+0x360+0x50), (double)*(float*)(res+0x360+0x54),
                            *(ET9U32*)(res+0x360+0x58),
                            (double)*(float*)(res+0x360+0x5c), (double)*(float*)(res+0x360+0x60),
                            *(ET9U32*)(res+0x360+0x64),
                            (double)*(float*)(res+0x360+0x68), (double)*(float*)(res+0x360+0x6c));
                XT9KDB_LOGI("  rec0[A] tag=%08x seq=%u cnt=%u start=(%.1f,%.1f) state=%u",
                            *(ET9U32*)(res+0x360+0x28), *(ET9U32*)(res+0x360+0x3c),
                            *(ET9U32*)(res+0x360+0x48), (double)*(float*)(res+0x360+0x50),
                            (double)*(float*)(res+0x360+0x54), *(ET9U32*)(res+0x360+0x44));
            }
        }
    }
    g_pst_calls++;

    if (!g_blob_pst) { XT9KDB_LOGE("PSt: blob original not found — dropping"); return ET9STATUS_ERROR; }
    ET9STATUS st = g_blob_pst(a0, a1, a2, a3, a4, a5, a6, a7);

    /* AFTER the blob decoded: where did the symbols land? Owning the AW feed needs the target
     * buffer. a0 is the ctx (validated by magic at +0x58). The tap symbol buffer is at ctx+0x52 —
     * our notes say a swipe leaves it empty, which would mean PST feeds AW elsewhere. Dump its
     * leading words plus the alpha object at ctx+0xAE210 so we can see which one PST populated. */
    if (xt9kdb_trace_dump_enabled() && a0 && *(ET9U16*)((char*)a0 + 0x58) == 0x1428u) {
        char* ctx = (char*)a0;
        /* Dump the WordSymbInfo at ctx+0x18750 as raw u32 words (every gesture while the XT9Trace
         * gate is on: 48 rows = 0x300 bytes, enough to expose the per-position SymbInfo stride for
         * offline structure decoding — collection sessions correlate each dump with a known word).
         * We feed the same buffer via ET9AddExplicitSymb, so this reveals the blob's OUTPUT SHAPE:
         * position count + whether positions hold single symbols or SETS. */
        unsigned char* wsi = (unsigned char*)ctx + 0x18750;
        {
            for (int row = 0; row < 48; row++) {
                ET9U32* w = (ET9U32*)(wsi + row * 16);
                XT9KDB_LOGI("PSt WSI +%03x: %08x %08x %08x %08x", row * 16, w[0], w[1], w[2], w[3]);
            }
        }
        /* Compact per-swipe line (every gesture): the blob's position count + the live NKL radii
         * its segmenter read (ctx+0x60 -> NKL; RADX=+0x38, RADY=+0x3c). */
        {
            unsigned char* nkl = *(unsigned char**)(ctx + 0x60);
            XT9KDB_LOGI("PSt post: WSI count(+0x02)=%u  liveNKL RADX=%u RADY=%u  st=%d",
                        *(ET9U16*)(wsi+0x02),
                        nkl ? *(ET9U32*)(nkl+0x38) : 0, nkl ? *(ET9U32*)(nkl+0x3c) : 0, (int)st);
        }
    }

    /* SHADOW decode (debug.et9.owndecode=2): run the owned decoder (kdb_decode.c) on the SAME
     * accumulated points, in blob-parity mode AND per-row mode, and log both next to the blob's
     * result. Compute + log only — the blob's WSI stands. This turns every daily-use swipe into a
     * passive parity/preview datapoint (remediation log §8.7.1 stage b). */
    if (owndecode_mode() >= 1 && g_n && g_kdb_model) {
        if (owndecode_mode() == 1) {
            static int warned = 0;
            if (!warned) { warned = 1; XT9KDB_LOGE("owndecode=1 (live) not wired yet - running SHADOW"); }
        }
        static Xt9DecPt  sp[MAX_SAMPLES];
        static Xt9DecPos gp[64], rp[64];
        for (ET9U32 i = 0; i < g_n; i++) {
            /* mirror the record builder: the blob consumed truncated unsigned coordinates */
            float fx = g_buf[i].x < 0.0f ? 0.0f : g_buf[i].x;
            float fy = g_buf[i].y < 0.0f ? 0.0f : g_buf[i].y;
            sp[i].x = (float)(ET9U32)fx; sp[i].y = (float)(ET9U32)fy; sp[i].t = g_buf[i].timestamp;
        }
        Xt9DecParams pg, pr;
        xt9kdb_decode_params_from_model(g_kdb_model, &pg, 0);
        xt9kdb_decode_params_from_model(g_kdb_model, &pr, 1);
        /* parity mode mirrors the LIVE RADY the blob read, debug.et9.rady overrides included */
        if (a0 && *(ET9U16*)((char*)a0 + 0x58) == 0x1428u) {
            unsigned char* nkl = *(unsigned char**)((char*)a0 + 0x60);
            if (nkl && *(ET9U32*)(nkl + 0x3c)) pg.rady = (float)*(ET9U32*)(nkl + 0x3c);
        }
        int ng = xt9kdb_decode_gesture(sp, g_n, g_kdb_model, &pg, gp, 64);
        int nr = xt9kdb_decode_gesture(sp, g_n, g_kdb_model, &pr, rp, 64);
        char s1[65], s2[65]; int k;
        for (k = 0; k < ng; k++) s1[k] = (gp[k].symbs[0] >= 32 && gp[k].symbs[0] < 127) ? (char)gp[k].symbs[0] : '?';
        s1[k] = 0;
        for (k = 0; k < nr; k++) s2[k] = (rp[k].symbs[0] >= 32 && rp[k].symbs[0] < 127) ? (char)rp[k].symbs[0] : '?';
        s2[k] = 0;
        XT9KDB_LOGI("OWNDEC shadow n=%u glob=%d '%s' | prow=%d '%s'", g_n, ng, s1, nr, s2);
    }
    return st;
}
#else
ET9STATUS XT9KDB(ProcessStoredTouch)(void* a0, ET9U64 a1, void* a2, ET9U64 a3,
                                     ET9U64 a4, ET9U64 a5, ET9U64 a6, ET9U64 a7) {
    (void)a0;(void)a1;(void)a2;(void)a3;(void)a4;(void)a5;(void)a6;(void)a7;
    return ET9STATUS_NONE;   /* no blob to forward to: offline or DIFF */
}
#endif


/* Resolve a sample (RAW sensor coords) to its key code (-1 if none). The stored path stays raw;
 * we map sensor->authored here so point_to_key works against the authored key rects. */
int xt9kdb_key_code_at(float sx, float sy, float* axo, float* ayo) {
    float ax, ay;
    xt9kdb_sensor_to_authored(sx, sy, &ax, &ay);
    if (axo) *axo = ax;
    if (ayo) *ayo = ay;
    int k = xt9kdb_point_to_key(g_kdb_model, ax, ay);
    return (k < 0) ? -1 : (int)g_kdb_model->keys[k].keyCode;
}
/* --- byte-exact result-block record writer (CUTOVER storage) --------------------------------------
 * RE-confirmed layout (TouchStart slot-alloc @0xbbb94 / sample writes @0xbcb64 / finalize):
 *   result = traceObj + 0x49000. TEN slots of 0x7568 at result+0x360 + slot*0x7568; slot 0's early
 *   words double as the header: result+0x370 = round-robin cursor (next slot to try), +0x374 = counter.
 *   Per-slot (relative to record): +0x28 sessionTag 0xBB786DC7, +0x30 startTime, +0x3c seqId,
 *   +0x40 finalize flags 0x00000101, +0x44 STATE (0=free / 2=finalized — also the slot-free probe),
 *   +0x48 sampleCount, +0x50 sample[0] {f32 x, f32 y, u32 t} stride 12. Body memset from +0x18 before init.
 * On-device DIFF (Xt9Trace.dumpTraceRec, XT9REC, 2026-07-04) confirmed +0x00..0x17 all-zero, the +0x28
 * tag, the +0x40 flags, and counter(0x374)==last-seqId. (Earlier docs put 0xAF5B3D8D at +0x28 — that is
 * actually the NKL format magic, a different field.) */
/* Result-block layout, kept for the XT9REC/xt9trace inspectors and the offline tests ONLY.
 * The owned writer that used these is GONE (2026-08-03): nothing polls this block for finished
 * records, so writing it never accomplished anything. Do NOT reintroduce a writer here.
 * In particular result+0x374 must stay ZERO -- ET9KDB_ProcessTrace bails with 0x66 unless it is
 * (0xca588/0xca58c), and nothing ever decrements it, so one stale write disables gestures for good.
 * Two beliefs this file used to assert are also wrong, per the stock-blob A/B: state(+0x44)==2
 * means "finger down" (TouchStart writes it before the first sample), not "finalized"; and
 * result+0x374 is an ACTIVE-TOUCH COUNT, not a pending-record count. */

static void   wr32(char* p, ET9U32 o, ET9U32 v) { memcpy(p + o, &v, 4); }
static ET9U32 rd32(char* p, ET9U32 o)           { ET9U32 v; memcpy(&v, p + o, 4); return v; }
static void   wrf (char* p, ET9U32 o, float  v) { memcpy(p + o, &v, 4); }

/* Write the accumulated gesture (g_buf[0..g_n)) as a FINALIZED record into a free slot, matching the
 * blob's TouchStart/Move/End so ET9_CP_Trace reads it unchanged. Returns the slot, or -1 if all busy. */


/* CUTOVER: store the accumulated gesture into the result block byte-exactly for the blob's recognizer.
 * (DIFF/scratch keeps decode_scratch + XT9OWNED separate; this path owns the storage, delegates scoring.) */
/* The exported name is interposable: libkb.so carries an R_AARCH64_JUMP_SLOT for
 * ET9KDB_ProcessTrace, and the blob (loaded first, and NOT UNDEF'd for this symbol -- it is absent
 * from elf_cutover.py's CONTRACT) wins global symbol lookup. So an internal call to the EXPORTED
 * name lands in the blob, which then reads gesture state we intercepted and never populated ->
 * SIGSEGV in ET9KDB_ProcessTrace+308, device-confirmed 2026-08-03.
 *
 * Callers inside this module must therefore use process_trace_impl, never XT9KDB(ProcessTrace).
 * Same class of defect as ctx+0x5a: owning half a subsystem means owning the seams between the
 * halves. */
/* Hand the accumulated path to the blob's OWN recognizer.
 *
 * Whole-.text scan (355,836 instructions, skipdata=True) settled the architecture: the recognition
 * dispatcher at 0x3d9c8 has exactly 15 call sites and EVERY one is inside
 * ET9KDB_TouchStart/Move/End/EndAll/Cancel/TimeOut. Nothing anywhere polls the result block for
 * finished records. Recognition is a synchronous PUSH from the Touch* entry points -- four of which
 * the cutover hands to us -- so once we own them, nobody kicks the scorer and a byte-perfect record
 * is inert. That is why months of record byte-parity work changed nothing: it was perfecting data
 * no code reads.
 *
 * ET9KDB_ProcessTrace @0xca4cc is the clean way back in: a complete standalone recognizer that
 * builds record[0] itself, arms the lock and drives ProcessStoredTouch. It has ZERO callers inside
 * the blob, so it is purely host-facing and safe for us to call.
 *
 * GATE (0xca588/0xca58c): it loads result+0x374 and bails with 0x66 unless that is ZERO. Our old
 * store_trace_record wrote 1 there, which is why it must be gone rather than merely unused --
 * nothing ever decrements it, so a single stale write disables the recognizer permanently. */

/* ---- owned ProcessTrace -----------------------------------------------------------------------
 * Replaces the blob's @0xca4cc on the gesture path. Safe to own because it has ZERO callers inside
 * the blob (pure host-facing API) — the only caller is our own TouchEnd — so this needs no ELF
 * contract change and cannot be reached behind our back.
 *
 * Deliberately NOT exported as ET9KDB_ProcessTrace. libkb.so carries a JUMP_SLOT for that name and
 * the blob wins global lookup, so defining it and calling it internally is the interposition trap
 * that SIGSEGV'd at ProcessTrace+308 (2026-08-03). This stays an internal symbol.
 *
 * What it does, per the live capture of the blob doing it (see TRACE_RESULT_REGION.md):
 *   validate ctx -> build record[0] at result+0x360 -> ProcessStoredTouch(ctx, mode, out, 1) once.
 * All decoding stays in ProcessStoredTouch; this only assembles its input.
 *
 * `setprop debug.et9.owntrace 0` falls back to the blob's original for A/B. */
#if defined(XT9KDB_CUTOVER) && defined(__ANDROID__)

/* Sample-array base within the record. The notes and the code header disagree (+0x5c vs +0x50);
 * the interpose dump above settles it per-build. Kept as a named constant so flipping it is one
 * edit, not a hunt. */
#define REC_SAMPLES_OFF 0x50u

#define BLOB_PROCESSTRACE_VADDR 0xca4ccu
typedef ET9STATUS (*xt9_blob_ptrace_fn)(ET9KDBInfoPtr, const ET9KdbTracePt*, ET9U32,
                                        const ET9U32*, ET9U8, ET9U16*);

static int owned_trace_enabled(void) {
    static int cached = -1;
    if (cached < 0) cached = read_prop_flag("debug.et9.owntrace", 1, XT9_PROP_OFF_CHAR);
    return cached;
}

/* ---- owned decoder + AW feed ------------------------------------------------------------------
 * Replaces the blob's ProcessStoredTouch decode with OUR geometry decoder and OUR
 * feed into AW's word engine. AW (the lexicon / selection-list build) stays the blob's — the scope
 * agreed 2026-08-12 is "decoder + AW feed", not the word engine itself.
 *
 * The feed target is the ET9WordSymbInfo at ctx+0x18750 (magic 0x1428 at offset 0 — the same
 * struct ET9ClearAllSymbs/ET9AddExplicitSymb/ET9AddCustomSymbolSet validate as their x0). Confirmed
 * empirically: after a blob swipe, ctx+0x52 is NOT a populated symbol buffer, so the old "ctx+0x52"
 * note does not apply to the trace path; the WordSymbInfo lives at +0x18750.
 *
 * The shipped feed is the AMBIGUOUS smart-touch set per decoded position (ET9AddCustomSymbolSet,
 * a 7-arg ABI) — see owned_pst_v2. The first cut fed EXACT symbols one per decoded key
 * (ET9AddExplicitSymb) to prove clear -> feed -> word end to end; it is superseded and no longer
 * ships (kdb_decode_legacy.c). Everything is called by address via the blob's load bias
 * (dl_iterate_phdr), like the ProcessKey/ProcessTrace trampolines, and every entry re-validates
 * the 0x1428 magic, so a wrong offset returns a status instead of crashing. */
#if defined(XT9KDB_CUTOVER) && defined(__ANDROID__)
#define BLOB_CLEAR_ALL_SYMBS   0xb5984u
#define BLOB_ADD_EXPLICIT_SYMB 0xb6e8cu
/* ET9AddCustomSymbolSet @0xb70a0 (public export; llvm-nm + disassembly 2026-08-14). ABI from the
 * wrapper's own validation code: (x0 wsi [magic 0x1428 checked], x1 u16* symbs, x2 u8* probs,
 * w3 count [0 -> status 7], w4 input-entry param [flows to the 0x3bbb4 bookkeeping helper; 0 is
 * the convention the proven explicit pipe uses], w5 shiftState [>2 -> status 26], w6 currIndex
 * byte). The wrapper picks the HIGHEST-PROB symbol as the default and forwards to the internal
 * 0xb55e0 — the same call the blob's own gesture feed loop makes (TRACE_RESULT_REGION pass 4). */
#define BLOB_ADD_CUSTOM_SET    0xb70a0u
#define WSI_OFFSET             0x18750u

/* ---- deposit-time selection list (W1, §8.7.14). The blob's JNI (buildSelectionList@0x20424,
 * getSelectionListWord@0x207c4) does NOT use a flat base — it calls FUNCTION POINTERS stored in
 * the engine object P = *(void**)(ctx + 0xAE210), with x0 = P:
 *   build   = (*(fn**)(P + 0x38))(P)            -> status (0 = OK)
 *   count   = (*(fn**)(P + 0x50))(P)            -> u16 candidate count
 *   getword = (*(fn**)(P + 0x58))(P, &wi, idx)  -> status; wi = 272B ET9AWWordInfo,
 *                                                  word u16[] @+0x00, length u32 @+0x80
 * Mirroring the JNI exactly avoids the flat-base guesswork that crashed (§8.7.14). Called
 * SYNCHRONOUSLY after the feed so no request-queue interleave can clear the sets (§8.7.13). */
#define ENGINE_P_OFF           0xAE210u    /* ctx -> *(engine object P) */
#define P_BUILD_FP             0x38u       /* fn ptr: buildSelectionList(P) */
#define P_COUNT_FP             0x50u       /* fn ptr: getSelectionListSize(P) */
#define P_GETWORD_FP           0x58u       /* fn ptr: getSelectionListWord(P, &wi, idx) */
#define WORDINFO_SIZE          0x110u      /* 272 */
#define WORDINFO_WORD_OFF      0x00u       /* u16[] */
#define WORDINFO_LEN_OFF       0x80u       /* u32 */

typedef ET9STATUS (*fn_clear_all)(void* wsi);
typedef ET9STATUS (*fn_add_explicit)(void* wsi, ET9U16 symb, ET9U32 a2, ET9U32 a3, ET9U8 flag);
typedef ET9STATUS (*fn_add_custom)(void* wsi, const ET9U16* symbs, const ET9U8* probs,
                                   ET9U32 count, ET9U32 a4, ET9U32 shiftState, ET9U8 currIndex);
typedef ET9STATUS (*fn_p_build)(void* P);
typedef ET9U32    (*fn_p_count)(void* P);
typedef ET9STATUS (*fn_p_getword)(void* P, ET9U16 index, void* wordInfoOut);  /* arg order per JNI @0x20858 */

static uintptr_t owned_blob_base(void) {
    static uintptr_t base = 0;
    static int done = 0;
    if (!done) { done = 1; dl_iterate_phdr(xt9_find_blob_pst_cb, &base); }
    return base;
}

/* ---- owned decode v2 (debug.et9.owndecode=1): kdb_decode.c + AMBIGUOUS-set feed --------------
 * The live path for the spec-faithful decoder (remediation log §8.7.3): run xt9kdb_decode_gesture
 * on the accumulated points (per-row thresholds per debug.et9.ownprow, default ON; dwell split
 * per debug.et9.owndwell, default OFF) and feed each position's smart-touch candidate SET through
 * the blob's public ET9AddCustomSymbolSet — the same per-position ambiguous-set feed the blob's
 * own gesture loop uses, so AW's word matching runs unchanged on OUR segmentation. */
static int own_v2_prop(const char* name, int dflt) {
    char v[PROP_VALUE_MAX];
    if (__system_property_get(name, v) > 0 && v[0] >= '0' && v[0] <= '9') return v[0] - '0';
    return dflt;
}

static ET9STATUS owned_pst_v2(void* ctx) {
    uintptr_t base = owned_blob_base();
    /* Belt-and-braces re-publish (TouchStart already did): the deposit must decode+rank
     * against the gesture owner's geometry even if a foreign ctx loaded mid-gesture. */
    { const ET9KdbLoaded* mm = xt9kdb_model_for_ctx(ctx); if (mm) xt9kdb_set_model(mm); }
    if (!base || !ctx || !g_kdb_model) { XT9KDB_LOGE("ownV2: no base/ctx/model"); return ET9STATUS_ERROR; }
    void* wsi = (char*)ctx + WSI_OFFSET;
    if (*(ET9U16*)wsi != 0x1428u) {
        XT9KDB_LOGF("ownV2: WordSymbInfo magic mismatch (0x%04x) — refusing", *(ET9U16*)wsi);
        return ET9STATUS_ERROR;
    }
    fn_clear_all  clear_all  = (fn_clear_all)(base + BLOB_CLEAR_ALL_SYMBS);
    fn_add_custom add_custom = (fn_add_custom)(base + BLOB_ADD_CUSTOM_SET);

    static Xt9DecPt  sp[MAX_SAMPLES];
    static Xt9DecPos pos[64];
    /* AUTHORED-space feed (VKB parity, 2026-08-19): the accumulated samples are view/sensor
     * coordinates. The blob's own decode maps them through the SetKeyboardSize stretch
     * (authored = authoredDim * view / scale — how the original app fits the KDB to the on-screen
     * VKB surface); the owned decoder must do the same or VKB swipes decode against the wrong
     * frame (hello->nelo). xt9kdb_sensor_to_authored IS that stretch: identity (+edge clamp)
     * when no scale is set (CKB/PKB — setKeyboardSize(0,0)), the stretch when the IME pushed the
     * VKB view dims. Everything downstream (decode, rank, recall) then works in authored space. */
    for (ET9U32 i = 0; i < g_n; i++) {
        float fx = g_buf[i].x < 0.0f ? 0.0f : g_buf[i].x;   /* mirror the record builder */
        float fy = g_buf[i].y < 0.0f ? 0.0f : g_buf[i].y;
        float ax, ay;
        xt9kdb_sensor_to_authored((float)(ET9U32)fx, (float)(ET9U32)fy, &ax, &ay);
        sp[i].x = ax; sp[i].y = ay; sp[i].t = g_buf[i].timestamp;
    }
    static int prow = -1, dwell = -1, fmin = -1, wpdev = -1;   /* cached: set props, then force-stop */
    static int fadapt = -1, fadaptlen = -1, xcross = -1;
    if (prow  < 0) prow  = own_v2_prop("debug.et9.ownprow",  1);
    if (dwell < 0) dwell = own_v2_prop("debug.et9.owndwell", 0);
    if (fmin  < 0) fmin  = own_v2_prop("debug.et9.ownfeedmin", 1);
    if (wpdev < 0) wpdev = own_v2_prop("debug.et9.ownwpdev", 0);   /* centi key-units; 0 = default */
    /* W6 sitting-1 decode robustness: key-crossing recovery for collinear pass-through letters
     * (coffee's f). Min samples in a distinct key cell to emit it. Default 6 — sitting-1 sweep
     * (cold): +1.3 ALL, double +6.9, long +3.5, ZERO short/plain/same-row cost; stable across 5-8.
     * Lower over-segments short words (owncross=2 -> short -15.6); 0 = OFF (deviation waypoint). */
    if (xcross < 0) xcross = own_v2_prop("debug.et9.owncross", 6);
    /* W6 sitting-1: the minimal feed UNDER-segments long sloppy swipes (buttered->bued,
     * kettles->kels — the real word never enters the pool), while feed_minimal=0 fixes long
     * recall (+3.5pt) but over-segments SHORT words (-6.6pt). So make the feed LENGTH-ADAPTIVE:
     * decode minimal first; if a dense re-decode yields a long word (>= ownfeedlen positions),
     * adopt the dense segmentation. Short words keep the minimal feed. Default OFF (A/B first). */
    if (fadapt    < 0) fadapt    = own_v2_prop("debug.et9.ownfeedadapt", 0);
    if (fadaptlen < 0) fadaptlen = own_v2_prop("debug.et9.ownfeedlen", 7);
    Xt9DecParams p;
    xt9kdb_decode_params_from_model(g_kdb_model, &p, prow);
    if (dwell > 0) p.dwell_min = dwell > 1 ? dwell : 7;    /* 1 = default threshold, N>1 = exact */
    p.feed_minimal = fmin;    /* generator recall wants clean minimal positions (§8.7.7 + W4 re-test) */
    if (wpdev > 0) p.wp_dev = wpdev / 100.0f;
    if (xcross > 0) p.cross_min = xcross;   /* key-crossing recovery (debug.et9.owncross) */

    int np = xt9kdb_decode_gesture(sp, g_n, g_kdb_model, &p, pos, 64);
    if (np <= 0) { XT9KDB_LOGE("ownV2: decode produced no positions — refusing feed"); return ET9STATUS_ERROR; }
    if (fadapt && fmin != 0) {
        static Xt9DecPos pos0[64];
        Xt9DecParams pd = p; pd.feed_minimal = 0;
        int np0 = xt9kdb_decode_gesture(sp, g_n, g_kdb_model, &pd, pos0, 64);
        if (np0 >= fadaptlen && np0 <= 64) {   /* long word: adopt the dense segmentation */
            for (int i = 0; i < np0; i++) pos[i] = pos0[i];
            XT9KDB_LOGI("ownV2: feed-adapt engaged (minimal np=%d -> dense np0=%d, len>=%d)", np, np0, fadaptlen);
            np = np0;
        }
    }

    ET9STATUS st = clear_all(wsi);
    char spell[65]; int spn = 0, fed = 0;
    for (int i = 0; i < np; i++) {
        if (!pos[i].nsymb) continue;
        st = add_custom(wsi, pos[i].symbs, pos[i].freqs, pos[i].nsymb, 0, 0, 0);
        if (st != ET9STATUS_NONE) { XT9KDB_LOGF("ownV2: AddCustomSymbolSet[%d] -> %d", i, (int)st); }
        else fed++;
        if (spn < 64) {
            ET9SYMB s = pos[i].symbs[0];
            spell[spn++] = (s >= 32 && s < 127) ? (char)s : '?';
        }
    }
    spell[spn] = 0;
    XT9KDB_LOGI("ownV2: fed %d/%d ambiguous sets (prow=%d dwell=%d) spell='%s'", fed, np, prow, dwell, spell);

    /* W1 (§8.7.14): rank AT DEPOSIT, in C, synchronously — the sets are guaranteed present (just
     * fed on this thread), so the §8.7.13 contamination (worker builds after an interleaved clear)
     * is structurally impossible. debug.et9.ownrankc overrides; default follows OWNED_DEFAULT
     * (ON in debug daily-driver builds, OFF in release until the §1 promotion bar is met).
     * Every deref guarded so a wrong offset logs and bails rather than crashing. */
    static int rankc = -1;
    if (rankc < 0) rankc = own_v2_prop("debug.et9.ownrankc", OWNED_DEFAULT);
    g_gesture_word_seq = 0;
    if (rankc && fed > 0) {
        /* Resolve engine object P and validate the three fn pointers are real code addresses
         * inside the blob before calling — a wrong layout logs and bails, never faults. */
        void* P = *(void**)((char*)ctx + ENGINE_P_OFF);
        uintptr_t blob_lo = base, blob_hi = base + 0x200000u;   /* libnative-lib is ~2 MB */
        uintptr_t fpB = P ? *(uintptr_t*)((char*)P + P_BUILD_FP)   : 0;
        uintptr_t fpC = P ? *(uintptr_t*)((char*)P + P_COUNT_FP)   : 0;
        uintptr_t fpW = P ? *(uintptr_t*)((char*)P + P_GETWORD_FP) : 0;
        int fp_ok = P && !((uintptr_t)P & 7)
            && fpB >= blob_lo && fpB < blob_hi && fpC >= blob_lo && fpC < blob_hi
            && fpW >= blob_lo && fpW < blob_hi;
        if (!fp_ok) {
            XT9KDB_LOGF("ownRankC: P=%p fn ptrs out of blob range (B=%p C=%p W=%p) — bailing",
                        P, (void*)fpB, (void*)fpC, (void*)fpW);
            return ET9STATUS_NONE;
        }
        /* The P build method returns a BOOLEAN (bit0 set = success — the JNI checks tbz w0,#0),
         * NOT an ET9STATUS. count comes from the P count method. */
        ET9STATUS bst = ((fn_p_build)fpB)(P);
        ET9U32 count = ((fn_p_count)fpC)(P);
        if (!((int)bst & 1) || count == 0 || count > 64) {
            XT9KDB_LOGF("ownRankC: build ret=%d count=%u — bailing to Java path", (int)bst, count);
        } else {
            static unsigned char wi[WORDINFO_SIZE];
            char cand[80];
            char bestw[80]; float bestScore = 1e9f; int bestIdx = -1; int bestRank = 0x7fffffff;
            static int rankmax = -1;
            if (rankmax < 0) { char v[PROP_VALUE_MAX];
                rankmax = (__system_property_get("debug.et9.rankmax", v) > 0) ? atoi(v) : 350; }
            /* W3 SELECTION (plan §W3, fitted OFFLINE on 4,613 synthetic + 64 real-trace
             * pools; fit and held-out real agree at ~67%, capturing 80% of the pool
             * oracle):
             *     s = geometry − W_FREQ·zipf(word) + (nonword echo ? W_ECHO : 0)
             * Geometry alone is frequency-blind (gate 9: vey/helo win tautologically);
             * blob index-0 alone is the tap echo (gate 11). The zipf prior (kdb_freq_en.h)
             * arbitrates geometric lookalikes (done 5.6 vs dome 3.9); the SOFT echo
             * penalty suppresses nonword skeletons without banning valid-word echoes —
             * §8.7.8's exception, soft form (hard exclusion lost the offline sweep).
             * English-only table for now; per-language = generated tables or an LDB
             * frequency probe (master-plan note). The decline guard stays on the pick's
             * raw GEOMETRY (contamination semantics unchanged), and the pool log keeps
             * logging raw geometry so the offline evaluator's data format is stable.
             * debug.et9.rankwf / rankwe: centi overrides (defaults 20 / 200). */
            static int wf_c = -1, we_c = -1, wd_c = -1, wc_c = -1, fc_c = -1, dwl_ms = -1, dwlp_ms = -1, dw_c = -1, dwp_c = -1, livefreq = -1, g_freqoff = 0x124;
            if (wf_c < 0) { char v[PROP_VALUE_MAX];
                /* default 25: fitted for the LIVE-frequency prior (log10 of the raw LDB count,
                 * ~0..6.4) — a touch above the wordfreq zipf scale's 20 (W6 real-corpus sweep:
                 * wf25 = 90.8%, matching the table's best). */
                wf_c = (__system_property_get("debug.et9.rankwf", v) > 0) ? atoi(v) : 25;
                we_c = (__system_property_get("debug.et9.rankwe", v) > 0) ? atoi(v) : 200;
                wd_c = (__system_property_get("debug.et9.rankwd", v) > 0) ? atoi(v) : 60;
                /* W6: LIVE LDB frequency prior (default ON) — language-independent, replaces
                 * the wordfreq table for pool candidates. 0 = fall back to the table. */
                livefreq = (__system_property_get("debug.et9.livefreq", v) > 0) ? atoi(v) : 1;
                /* W6-C: which 616B-entry frequency field the prior reads. debug.et9.freqoff =
                 * 0 (default) -> 0x124 LDB+DLM freq; 1 -> 0x128; 2 -> 0x12c (candidate context
                 * freq). One-flip lever for the paragraph-corpus context A/B. */
                int fc = (__system_property_get("debug.et9.freqoff", v) > 0) ? atoi(v) : 0;
                g_freqoff = (fc == 2) ? 0x12c : (fc == 1) ? 0x128 : 0x124;
                /* W6-C context-LIFT (debug.et9.rankwc, centi, default 0 = off): add
                 * -(wc/100)*(log10(f@0x12c) - log10(f@0x124)) to the blend. Drop-in freqoff=2
                 * was measured NET NEGATIVE (corpus_v2 59->53; done->some x5 across differing
                 * contexts, i.e. 0x12c's dominant component is static per-word inflation, not
                 * P(word|context)) - the lift form keeps 0x124 as the anchor so any genuine
                 * context component in 0x12c can only nudge, and wc=0 is bit-identical to
                 * today. Pool candidates only (recall words have no engine entry). */
                wc_c = (__system_property_get("debug.et9.rankwc", v) > 0) ? atoi(v) : 0;
                /* Live-freq CLAMP (debug.et9.rankfc, centi-zipf halfwidth; 0 = off): bound the
                 * live-freq term within +/-fc of the stable table zipf for words the table knows.
                 * The +0x124 live value swings ~100x between queries (W5 finding); the raw prior
                 * is strongly net-positive (removing it: VKB 212->198) but its noise tail flips
                 * geometry-better candidates (sweet lost to at on a >2.5-decade inflation). The
                 * clamp keeps DLM personalization and fine ordering, kills only the tail.
                 * Non-English/unknown words have z=0 and are left unclamped. */
                fc_c = (__system_property_get("debug.et9.rankfc", v) > 0) ? atoi(v) : 0;
                /* dwell-evidence double bonus, per-surface contiguous-dwell thresholds:
                 * debug.et9.dwellms = VKB threshold in ms (default 400; corpus: 88% double-hit,
                 * 1.5% false; doubles 43->50/56), debug.et9.dwellmspkb = CKB threshold (default
                 * 350; corpus: 76% hit, 2% false — the owner pauses on doubles on the physical
                 * pad too: 454ms median vs 165ms pass-through. W4's "no separation" measured
                 * decode-CLUSTER durations for feed emission, a different feature). 0 disables
                 * that surface. debug.et9.rankdw = centi bonus weight (default 60). */
                dwl_ms = (__system_property_get("debug.et9.dwellms", v) > 0) ? atoi(v) : 400;
                dwlp_ms = (__system_property_get("debug.et9.dwellmspkb", v) > 0) ? atoi(v) : 400;
                dw_c = (__system_property_get("debug.et9.rankdw", v) > 0) ? atoi(v) : 60;
                /* Per-surface WEIGHT: the VKB needs 0.60 (too->to must out-bid `to`'s rank-2
                 * frequency, a ~1.7-zipf gap), but on the CKB 0.60 overpowers real frequency
                 * gaps between path-identical pairs (drop->droop, ~0.38) while the true CKB
                 * double fixes (hello/coffee) are 0.01-0.04 coin-flips needing only a nudge —
                 * so the CKB weight is gentle (swept: 0.60 breaks drop->droop, 0.35 loses a hello fix; 0.45 = ALL 61/69 PASS). */
                dwp_c = (__system_property_get("debug.et9.rankdwpkb", v) > 0) ? atoi(v) : 45; }
            /* W6 LOCALE GATE: the LIVE-frequency prior is language-independent (always on),
             * but the English-lexicon pieces — W5 owned recall (kdb_freq_en.h) and the
             * wordfreq-table echo/double heuristics — are valid only for English. Read the
             * active LDB language once; for non-English keep the language-independent path
             * and drop the English-only refinements. debug.et9.langgate=0 forces English
             * treatment (the pre-W6 behaviour) for A/B. */
            static int english = -1, langid = -2, langgate = -1;
            if (english < 0) { char v[PROP_VALUE_MAX];
                langgate = (__system_property_get("debug.et9.langgate", v) > 0) ? atoi(v) : 1;
                langid = xt9_active_lang(base, P);
                /* ET9 English primary-language ids (US/UK/…) share the 0x0009 low byte. */
                english = (!langgate) || (langid < 0) || ((langid & 0xff) == 0x09);
                XT9KDB_LOGI("ownRankC locale: langid=0x%x english=%d gate=%d", langid, english, langgate); }
            char lspell[80]; { int j = 0; for (; spell[j] && j < 79; j++) lspell[j] = (spell[j]>='A'&&spell[j]<='Z')?spell[j]+32:spell[j]; lspell[j]=0; }
            /* echo/double heuristics use the English table — only meaningful for English. */
            const int echoNonword = english && (freq_zipf10(lspell) < 28);
            /* per-surface dwell threshold — surface can flip within a process (KEY2 PKB<->VKB) */
            const int dwell_thr = xt9kdb_active_pkb() ? dwlp_ms : dwl_ms;
            const int dwell_w = xt9kdb_active_pkb() ? dwp_c : dw_c;
            const int dwell_on = dwell_thr > 0 && dwell_w > 0;
            float bestGeo = 1e9f;
            char poollog[1500]; int pl = 0;  /* full 32-candidate pools: offline policy eval mines these */
            for (ET9U16 gi = 0; gi < count; gi++) {
                memset(wi, 0, WORDINFO_SIZE);
                if (!((int)((fn_p_getword)fpW)(P, gi, wi) & 1)) continue;   /* boolean: bit0=ok */
                ET9U32 wlen = *(ET9U32*)(wi + WORDINFO_LEN_OFF);
                if (wlen == 0 || wlen > 63) continue;
                const ET9U16* wc = (const ET9U16*)(wi + WORDINFO_WORD_OFF);
                int k = 0; for (; k < (int)wlen; k++) cand[k] = (wc[k] >= 32 && wc[k] < 127) ? (char)wc[k] : '?';
                cand[k] = 0;
                float geo = xt9kdb_rank_score(g_kdb_model, &p, sp, g_n, cand, (int)gi);
                if (pl < 1440) pl += snprintf(poollog + pl, sizeof(poollog) - pl, "%d:%s=%.2f ", gi, cand, (double)geo);
                char lc[80]; { int j = 0; for (; cand[j] && j < 79; j++) lc[j] = (cand[j]>='A'&&cand[j]<='Z')?cand[j]+32:cand[j]; lc[j]=0; }
                /* Frequency prior: LIVE engine frequency (W6, language-independent) when
                 * available, else the wordfreq table. log10 puts the raw count (~1..2.4M) on
                 * the same ~0..6 scale the zipf table used, so wf_c carries over. */
                float lf = livefreq ? xt9_live_freq(base, P, (int)gi, g_freqoff) : -1.0f;
                float freqterm = (lf > 0.0f) ? log10f(lf) : (freq_zipf10(lc) / 10.0f);
                if (fc_c > 0 && lf > 0.0f) {
                    int z = freq_zipf10(lc);
                    if (z > 0) {
                        float lo = z / 10.0f - fc_c / 100.0f, hi = z / 10.0f + fc_c / 100.0f;
                        freqterm = freqterm < lo ? lo : freqterm > hi ? hi : freqterm;
                    }
                }
                float s = geo - (wf_c / 100.0f) * freqterm;
                if (wc_c > 0) {
                    float f0 = xt9_live_freq(base, P, (int)gi, 0x124);
                    float fx = xt9_live_freq(base, P, (int)gi, 0x12c);
                    if (f0 > 0.0f && fx > 0.0f) s -= (wc_c / 100.0f) * (log10f(fx) - log10f(f0));
                }
                if (echoNonword && !strcmp(lc, lspell)) s += we_c / 100.0f;
                if (wd_c > 0 && echoNonword && is_double_expansion(lc, lspell)) s -= wd_c / 100.0f;
                if (dwell_on && dbl_dwell_support(g_kdb_model, sp, g_n, lc, dwell_thr)) s -= dwell_w / 100.0f;
                int rk = freq_rank(lc);   /* tie-break toward the more-common word on identical scores */
                if (s < bestScore - 1e-4f || (s < bestScore + 1e-4f && rk < bestRank)) {
                    bestScore = s; bestGeo = geo; bestIdx = gi; bestRank = rk; int j = 0;
                    for (; cand[j]; j++) bestw[j] = cand[j]; bestw[j] = 0;
                }
            }
            XT9KDB_LOGI("ownRankC pool: %s", poollog);
            /* W5: owned trace-native recall — union with the AW pool under the same blend.
             * Recall candidates carry bestIdx = 100+i so logs distinguish the source.
             * LOCALE GATE (W6): the recall lexicon (kdb_freq_en.h) is English — inject it only
             * for English; other languages rely on the (language-independent) AW pool + live
             * frequency prior, so injecting English words is suppressed. */
            static int recall_on = -1;
            if (recall_on < 0) recall_on = own_v2_prop("debug.et9.ownrecall", 1);
            if (recall_on && english) {
                int rIdx[RC_TOP]; float rGeo[RC_TOP];
                int rn = rc_recall(sp, g_n, &p, rIdx, rGeo);
                char rlog[400]; int rl = 0;
                for (int ri = 0; ri < rn; ri++) {
                    const char* w = kFreqWordsEn[rIdx[ri]];
                    if (rl < 340) rl += snprintf(rlog + rl, sizeof(rlog) - rl, "%s=%.2f ", w, (double)rGeo[ri]);
                    float s = rGeo[ri] - (wf_c / 100.0f) * (kFreqZipfEn[rIdx[ri]] / 10.0f);
                    if (echoNonword && !strcmp(w, lspell)) s += we_c / 100.0f;
                    if (wd_c > 0 && echoNonword && is_double_expansion(w, lspell)) s -= wd_c / 100.0f;
                    if (dwell_on && dbl_dwell_support(g_kdb_model, sp, g_n, w, dwell_thr)) s -= dwell_w / 100.0f;
                    int rk = kFreqRankEn[rIdx[ri]];
                    if (s < bestScore - 1e-4f || (s < bestScore + 1e-4f && rk < bestRank)) {
                        bestScore = s; bestGeo = rGeo[ri]; bestIdx = 100 + ri; bestRank = rk; int j = 0;
                        for (; w[j] && j < (int)sizeof(bestw) - 1; j++) bestw[j] = w[j];
                        bestw[j] = 0;
                    }
                }
                if (rn) XT9KDB_LOGI("ownRecall top: %s", rlog);
            }
            int declined = (rankmax > 0 && bestIdx >= 0 && bestGeo * 100.0f > (float)rankmax);
            if (bestIdx >= 0 && !declined) {
                int j = 0; for (; j < (int)sizeof(g_gesture_word) - 1 && bestw[j]; j++) g_gesture_word[j] = bestw[j];
                g_gesture_word[j] = 0;
                g_gesture_word_seq = xt9kdb_rank_seq();
            }
            XT9KDB_LOGI("ownRankC: count=%u best='%s' score=%.2f%s seq=%u",
                        count, bestIdx >= 0 ? bestw : "-", (double)bestScore,
                        declined ? " DECLINED" : "", g_gesture_word_seq);
            /* W6-A DLM audit probe: log the winner's live frequency so a repeated-swipe test
             * can watch it rise as the DLM learns the committed word. debug.et9.winfreq=1. */
            { static int wfq = -2; if (wfq == -2) { char v[PROP_VALUE_MAX];
                wfq = (__system_property_get("debug.et9.winfreq", v) > 0) ? atoi(v) : 0; }
              if (wfq && bestIdx >= 0 && bestIdx < 64) {
                void* alpha = *(void**)P; void* ep = 0;
                typedef int (*fn_slg)(void*, void**, int);
                ((fn_slg)(base + 0xef7e4u))((char*)alpha + 0x8, &ep, bestIdx);
                if (ep) XT9KDB_LOGI("WINFREQ %s f124=%.0f f12c=%.0f", bestw,
                    (double)*(float*)((char*)ep + 0x124), (double)*(float*)((char*)ep + 0x12c));
              } }
        }
    }
    return ET9STATUS_NONE;
}
#endif

static ET9STATUS owned_process_trace(ET9KDBInfoPtr ctx, const ET9KdbTracePt* pts, ET9U32 count,
                                     const ET9U32* times, ET9U8 mode, ET9U16* out) {
    /* Validator chain mirroring 0xca4cc..0xca558. Same order, same status codes. */
    if (!ctx || !out) return ET9STATUS_INVALID_MEMORY;
    char* c = (char*)ctx;
    ET9U16 magic = *(ET9U16*)(c + 0x58);
    if (magic != 0x1428u)                  return (ET9STATUS)2;
    if (*(ET9U8*)(c + 0x38))               return (ET9STATUS)2;   /* busy */
    if (*(ET9U16*)(c + 0x5a) != magic)     return (ET9STATUS)0x27; /* no KDB loaded */
    char* tr = *(char**)(c + 0x30);
    if (!tr)                               return ET9STATUS_INVALID_MEMORY;
    if (*(ET9U16*)tr != magic)             return (ET9STATUS)2;
    if (!count || !pts || !times)          return ET9STATUS_NONE;

    char* res = tr + 0x49000;
    /* The blob refuses unless this is zero, and nothing ever decrements it. Owning ProcessTrace
     * does not license writing it — ProcessStoredTouch reads the same field. */
    if (rd32(res, 0x374) != 0) {
        XT9KDB_LOGF("owned ProcessTrace: result+0x374=%u (expected 0) - refusing", rd32(res, 0x374));
        return (ET9STATUS)0x66;
    }

    char* rec = res + 0x360;                      /* record[0]; confirmed live 2026-08-12 */
    ET9U32 cap = (0x7568u - REC_SAMPLES_OFF) / 12u;
    if (count > cap) count = cap;

    memset(rec + 0x18, 0, 0x38);                  /* body clear from +0x18, as the blob does */
    *(ET9U8*)(rec + 0x00) = 1;                    /* observed set to 1 immediately before the call */
    wr32(rec, 0x04, 0);
    wr32(rec, 0x08, 1);
    /* Session tag is per-KDB: NKL+0x0c, the loaded layout's content checksum. ProcessTrace reads
     * it as [[ctx+0x60]+0xc]. Hardcoding it is wrong the moment the layout changes. */
    {
        char* nkl = *(char**)(c + ET9_OFF_NKL);
        wr32(rec, 0x28, nkl ? rd32(nkl, 0x0c) : ET9_SESSION_TAG);
    }
    wr32(rec, 0x30, times[0]);                    /* start time  */
    wr32(rec, 0x3c, 0);                           /* sequence id */
    wr32(rec, 0x40, 0x00000101u);                 /* finalize flags */
    wr32(rec, 0x44, 3);                           /* mode: 3 = gesture (0 = tap) */
    wr32(rec, 0x48, count);                       /* sampleCount */
    for (ET9U32 i = 0; i < count; i++) {
        ET9U32 o = REC_SAMPLES_OFF + i * 12u;
        wrf (rec, o + 0, (float)pts[i].x);
        wrf (rec, o + 4, (float)pts[i].y);
        wr32(rec, o + 8, times[i]);
    }

    *out = 0;
    /* Own the decode + AW feed instead of handing the record to the blob's ProcessStoredTouch. The
     * record[0] above is still built (it is cheap and keeps the blob's view consistent).
     * debug.et9.owndecode=1 -> the v2 path (kdb_decode.c + ambiguous sets, §8.7.3); anything else
     * hands the record back to the blob. The superseded first-cut path (debug.et9.ownpst ->
     * decode_keyseq + explicit symbols) no longer ships: see kdb_decode_legacy.c. */
    if (owndecode_mode() == 1) {
        return owned_pst_v2(ctx);
    }
    return XT9KDB(ProcessStoredTouch)(ctx, (ET9U64)mode, out, 1, 0, 0, 0, 0);
}
#endif

#if defined(XT9KDB_CUTOVER) && defined(__ANDROID__)
#include <dlfcn.h>
extern ET9STATUS ET9KDB_ProcessTrace(ET9KDBInfoPtr, const ET9KdbTracePt*, ET9U32,
                                     const ET9U32*, ET9U8, ET9U16*) __attribute__((weak));
typedef ET9STATUS (*xt9_blob_trace_fn)(ET9KDBInfoPtr, const ET9KdbTracePt*, ET9U32,
                                       const ET9U32*, ET9U8, ET9U16*);

/* The blob's ET9KDB_ProcessTrace, resolved even when the weak reference below came up NULL.
 *
 * The weak reference binds only if the blob is already loaded when libkb.so is relocated
 * (BIND_NOW). That holds when the blob loads libkb.so as its DT_NEEDED — but Xt9KdbVariant loads
 * libkb.so on its own from DeviceProfile.initialize, and ComposeSettingsActivity calls that. So a
 * process started by keyboard settings loads libkb.so ~2 s before NuanceSDK loads the blob, the
 * weak symbol resolves to NULL, and the loader never revisits it: every swipe for the life of
 * that process failed with "blob symbol did not bind" (KEY2, 2026-09-15; latent since 26ca82a6).
 *
 * Fall back to looking the exported symbol up in the already-loaded blob. RTLD_NOLOAD never loads
 * it, only finds it. A miss is not cached — the blob may simply not be loaded yet — but a hit is. */
static xt9_blob_trace_fn blob_process_trace(void) {
    if (&ET9KDB_ProcessTrace) return ET9KDB_ProcessTrace;
    static xt9_blob_trace_fn resolved;
    if (!resolved) {
        void* blob = dlopen("libnative-lib.so", RTLD_NOW | RTLD_NOLOAD);
        if (blob) {
            resolved = (xt9_blob_trace_fn)dlsym(blob, "ET9KDB_ProcessTrace");
            dlclose(blob);   /* drops only the reference RTLD_NOLOAD added */
            XT9KDB_LOGI("ProcessTrace: weak ref was NULL (libkb loaded before the blob); "
                        "resolved late -> %p", (void*)resolved);
        }
    }
    return resolved;
}
#endif

static ET9STATUS process_trace_impl(ET9KDBInfoPtr ctx) {
    /* L10: no context is "the recognizer could not run", not "nothing to recognize". Counted in
     * every mode, because a NULL handle is a contract violation wherever it happens. */
    if (!ctx) { g_rec_unavailable++; XT9KDB_LOGE("ProcessTrace: ctx NULL"); return ET9STATUS_INVALID_MEMORY; }
    if (g_n == 0) { XT9KDB_LOGE("ProcessTrace: nothing accumulated"); return ET9STATUS_NONE; }

    static ET9KdbTracePt pts[MAX_SAMPLES];
    static ET9U32        times[MAX_SAMPLES];
    ET9U16 out = 0;
    ET9U32 n = g_n;
    for (ET9U32 i = 0; i < g_n; i++) {
        float fx = g_buf[i].x < 0.0f ? 0.0f : g_buf[i].x;   /* 0xca608/0xca610 ucvtf => UNSIGNED */
        float fy = g_buf[i].y < 0.0f ? 0.0f : g_buf[i].y;
        pts[i].x = (ET9U32)fx; pts[i].y = (ET9U32)fy;
        times[i] = g_buf[i].timestamp;
    }
/* __ANDROID__ as well as CUTOVER: the offline cutover selftest compiles with -DXT9KDB_CUTOVER but
 * links no blob, so the symbol would be an unresolvable UNDEF there.
 *
 * WEAK because libkb.so is linked standalone -- the blob is not a link-time input, so a strong
 * reference fails with "undefined symbol: ET9KDB_ProcessTrace". At runtime the blob is already
 * loaded and exports it, so the weak reference binds. If it ever does NOT bind we get a NULL we
 * can log, rather than a load failure or a jump to zero. */
#if defined(XT9KDB_CUTOVER) && defined(__ANDROID__)
extern ET9STATUS ET9KDB_ProcessTrace(ET9KDBInfoPtr, const ET9KdbTracePt*, ET9U32,
                                     const ET9U32*, ET9U8, ET9U16*) __attribute__((weak));
    /* mode 0xFF mirrors the blob's own kdbRequestHandler (0x1fba4 `mov w1,#0xff`).
     * `out` must be non-NULL: 0xc6678 returns 9 on a NULL out-param.
     * Only in CUTOVER: this resolves to the blob's ET9KDB_ProcessTrace, which is absent from
     * elf_cutover.py's CONTRACT and therefore still defined by the blob. In DIFF/offline builds
     * XT9KDB(name) is xt9kdb_##name and there is no blob to call at all. */
    xt9_blob_trace_fn blob_trace = blob_process_trace();
    if (!blob_trace) {
        g_rec_unavailable++;   /* L10: the one failure that kills swipe for the whole process */
        XT9KDB_LOGE("ProcessTrace: blob symbol did not bind — gesture recognition unavailable");
        return ET9STATUS_NONE;
    }
    xt9kdb_rank_snapshot_store();   /* deposit-time path snapshot for the owned ranker (§8.7.10) */
    ET9STATUS st;
    if (owned_trace_enabled()) {
        st = owned_process_trace(ctx, pts, n, times, 0xFF, &out);
        XT9KDB_LOGI("ProcessTrace(OWNED) n=%u st=%d out=%u", n, (int)st, (unsigned)out);
    } else {
        st = blob_trace(ctx, pts, n, times, 0xFF, &out);
        XT9KDB_LOGI("ProcessTrace(blob) n=%u st=%d out=%u", n, (int)st, (unsigned)out);
    }
    if (st != ET9STATUS_NONE) g_rec_failures++;   /* L10: TouchEnd is about to swallow this */
    return st;
#else
    (void)pts; (void)times; (void)out; (void)n;   /* no blob to call: offline, or a DIFF build */
    return ET9STATUS_NONE;
#endif
}

const void* XT9KDB(_GetLastTrace)(ET9KDBInfoPtr ctx)    { (void)ctx; return g_buf; }
const void* XT9KDB(_GetLastTraceDbg)(ET9KDBInfoPtr ctx) { (void)ctx; return g_buf; }

/* Expose the current gesture's raw samples to GetKeyPositionByStoredTouch (kdb_geometry.c). */
int xt9kdb_stored_sample(ET9U32 idx, float* x, float* y) {
    if (idx >= g_n) return 0;
    if (x) *x = g_buf[idx].x;
    if (y) *y = g_buf[idx].y;
    return 1;
}

/* ---- rank-path snapshot (§8.7.10) --------------------------------------------------------------
 * The owned ranker must score against the DEPOSITED gesture's path, never the live buffer:
 * g_buf is overwritten by the NEXT swipe's TouchStart/Move on the main thread with no lock
 * involved, so a worker-thread rank that reads it races (complete next path -> off-by-one
 * winners; partial next path -> garbage winners — both observed on corpus-A). This snapshot is
 * written ONCE per gesture at ProcessTrace time (deposit), and the next deposit is serialized
 * behind the Java gesture lock that the bridge holds through ranking — so it is stable exactly
 * for the window the ranker needs. */
static ET9KdbSample g_rank_buf[MAX_SAMPLES];
static ET9U32            g_rank_n;
static ET9U32            g_rank_seq;    /* deposit sequence — consume-once key (§8.7.11) */

void xt9kdb_rank_snapshot_store(void) {
    memcpy(g_rank_buf, g_buf, sizeof(g_buf[0]) * g_n);
    g_rank_n = g_n;
    g_rank_seq++;
    XT9KDB_LOGI("rank snapshot: seq=%u n=%u", g_rank_seq, g_rank_n);
}

ET9U32 xt9kdb_rank_seq(void) { return g_rank_seq; }

int xt9kdb_rank_sample(ET9U32 idx, float* x, float* y) {
    if (idx >= g_rank_n) return 0;
    if (x) *x = g_rank_buf[idx].x;
    if (y) *y = g_rank_buf[idx].y;
    return 1;
}
